### ISSUE TITLE
[ToDo] Finish Documentation in the Wiki Section

### ISSUE THREAD

**Issue by TheKye** [TheKye/EM-Framework#8]
These pages need the documentation written up for that section 

- [ ] [Eco.EM.Framework.Text](https://github.com/TheKye/EM-Framework/wiki/Eco.EM.Framework.Text)
- [ ] [Animal Trapping](https://github.com/TheKye/EM-Framework/wiki/Animal-Trapping)
- [ ] [Autodoor](https://github.com/TheKye/EM-Framework/wiki/Autodoor)
- [ ] [Eco.EM.Framework.Discord](https://github.com/TheKye/EM-Framework/wiki/Eco.EM.Framework.Discord)
- [ ] [Eco.EM.Framework.Discord.NET](https://github.com/TheKye/EM-Framework/wiki/Eco.EM.Framework.Discord.NET)
- [ ] [Eco.EM.Framework.Extentsions](https://github.com/TheKye/EM-Framework/wiki/Eco.EM.Framework.Extentsions)
- [ ] [Eco.EM.Framework.Listeners](https://github.com/TheKye/EM-Framework/wiki/Eco.EM.Framework.Listeners)
- [ ] [Eco.EM.Framework.Logging](https://github.com/TheKye/EM-Framework/wiki/Eco.EM.Framework.Logging)
- [ ] [Eco.EM.Framework.Networking](https://github.com/TheKye/EM-Framework/wiki/Eco.EM.Framework.Networking)
- [ ] [Eco.EM.Framework.UI](https://github.com/TheKye/EM-Framework/wiki/Eco.EM.Framework.UI)
- [ ] [Eco.EM.Framework.VersioningTools](https://github.com/TheKye/EM-Framework/wiki/Eco.EM.Framework.VersioningTools)

These Sections need documentation update for changes

- [ ] [Eco.EM.Framework.Utils](https://github.com/TheKye/EM-Framework/wiki/Eco.EM.Framework.Utils)
* Could also be broken up into seperate pages i guess

- [ ] [Eco.EM.Framework.Helpers](https://github.com/TheKye/EM-Framework/wiki/Eco.EM.Framework.Helpers)
